### PR TITLE
Bookstore: Use Redux in React components.

### PR DESCRIPTION
**Pull request by Hisoka37**
## In this PR I:

- Wrap  `<App>` with the `<Provider>` component from `react-redux`
- Pass  configured `store` into the `<Provider>`
- Display  `books`, received from the slice, in a reusable component
- Dispatch actions using `useDispatch`
- Add a `<Button>` component, which includes:
  - An event handler that **adds** a book to the `books` array (with attributes _id_, _title_ and _author_)
- Add a `<Button>` component, which includes:
  - An event handler that **removes** a book from the `books` array (by _id_)

Cheers and happy coding 😍

### CODE REVIEW

**Review by fobadara — COMMENTED** [review]
Hi @Hisoka37, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with a live demo section in its README without a working. live demo link. Kindly include one or remove the entire section if. it is not a requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Hisoka37** [comment]
Hi @fobadara , I really can't understand why you made it invalid, because the live demo was just a text mentioning that I would add it soon, it's not a harm to the project, can you please explain why you think it's a problem?

**Comment by ABDULALI3468** [comment]
@fobadara He @Hisoka37  asked you because it's a project requirement to have a professional README and in README requirements its manadatory to either remove the live demo section (when it's not asked to make it live only) or make the project live and add the respective link. HOPE THAT HELPS! 👍

**Comment by Hisoka37** [comment]
@ABDULALI3468 , Thank you ✌️

**Comment by ABDULALI3468** [comment]
@Hisoka37 My absolute pleasure!

**Review by ABDULALI3468 — APPROVED** [review]
Hi @Hisoka37 , 👍 

# APPROVED 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights 

✅APP logic is working as expected.
✅Good use of REDUX.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: GitHub followers
> * This is My **Linkedin**: [Linkedin Badge](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [Twitter Badge](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
